// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCtY5DTmgP5EqKv9tSJeTDhZZfUqlBFTU',
    appId: '1:870897470897:web:cc4b74ed75c4ae775b8190',
    messagingSenderId: '870897470897',
    projectId: 'authtutorial-f575c',
    authDomain: 'authtutorial-f575c.firebaseapp.com',
    storageBucket: 'authtutorial-f575c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl6sLjB06GwYNTFLhlBT_USPlfmF7CO_8',
    appId: '1:870897470897:android:7321f267f3593eb85b8190',
    messagingSenderId: '870897470897',
    projectId: 'authtutorial-f575c',
    storageBucket: 'authtutorial-f575c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-7P7BpmnUlr1xVFeRm3mL5MvTLpplzqs',
    appId: '1:870897470897:ios:09c6ad7b0d229c845b8190',
    messagingSenderId: '870897470897',
    projectId: 'authtutorial-f575c',
    storageBucket: 'authtutorial-f575c.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-7P7BpmnUlr1xVFeRm3mL5MvTLpplzqs',
    appId: '1:870897470897:ios:3fb72e05725300f55b8190',
    messagingSenderId: '870897470897',
    projectId: 'authtutorial-f575c',
    storageBucket: 'authtutorial-f575c.appspot.com',
    iosBundleId: 'com.example.testApp.RunnerTests',
  );
}
